language: generic 
sudo: required
services: 
  - docker


before_install:
  - docker build -t khojii/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khojii/docker-react npm run test