version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /local/app/node_modules
      - .:/local/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /local/app/node_modules
      - .:/local/app
    command: ["npm", "run", "test"]